module.exports = {
    errors: {
        ERR_HEADER_MISSED: 'ERR_HEADER_MISSED',
        ERR_SESSION_KEY_EXCHANGE_FAILED: 'ERR_SESSION_KEY_EXCHANGE_FAILED',
        ERR_UNTRUSTED_DATA: 'ERR_UNTRUSTED_DATA',
        ERR_SESSION_INVALID: 'ERR_SESSION_INVALID',
        ERR_OTHERS: 'ERR_OTHERS'
    }
}
